[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[server]
address = "127.0.0.1"
port = 8501

[theme]
base = "light"
primaryColor = "#25668c"
backgroundColor = "#e8eff6"
secondaryBackgroundColor = "#f7fafc"
textColor = "#153247"
font = "sans-serif"
